#[derive(clap::ValueEnum, Clone)]
pub enum Shell {
    Zsh,
    Bash,
}

#[derive(clap::Args)]
pub struct InitArgs {
    pub shell: Shell,
}

fn is_valid_shell_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' => {}
        _ => return false,
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

pub fn run(args: InitArgs) -> Result<(), String> {
    let name =
        crate::git::config::read_string("mate.wrapperName").unwrap_or_else(|| "gm".to_string());

    if !is_valid_shell_identifier(&name) {
        return Err(format!(
            "invalid wrapper name {name:?}: must match [A-Za-z_][A-Za-z0-9_]*"
        ));
    }

    print!("{}", shell_init(&name, &args.shell));
    Ok(())
}

fn shell_init(name: &str, shell: &Shell) -> String {
    let (shell_name, completion) = match shell {
        Shell::Zsh => ("zsh", ZSH_COMPLETION),
        Shell::Bash => ("bash", BASH_COMPLETION),
    };
    INIT_TEMPLATE
        .replace("{SHELL}", shell_name)
        .replace("{COMPLETION_SETUP}", completion)
        .replace("{NAME}", name)
}

const INIT_TEMPLATE: &str = r#"# git-mate shell integration — generated by `git mate init {SHELL}`
# Add to ~/.{SHELL}rc: eval "$(git mate init {SHELL})"

function {NAME}() {
    case "$1" in
        co)     _git_mate_checkout "${@:2}" ;;
        new)    _git_mate_new      "${@:2}" ;;
        finish) _git_mate_finish   "${@:2}" ;;
        *)      command git "$@" ;;
    esac
}

function _git_mate_run() {
    local subcmd=$1; shift
    local stdout exit_code cd_path
    stdout=$(GIT_MATE_SHELL=1 command git mate "$subcmd" "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}

function _git_mate_checkout() { _git_mate_run checkout "$@"; }
function _git_mate_new()      { _git_mate_run new      "$@"; }
function _git_mate_finish()   { _git_mate_run finish   "$@"; }

{COMPLETION_SETUP}"#;

const ZSH_COMPLETION: &str = r#"function _git_mate_complete() {
    local -a candidates
    candidates=(${(f)"$(COMPLETE=zsh command git-mate -- "${words[@]:1}" 2>/dev/null)"})
    compadd -a candidates
}
compdef _git_mate_complete git-mate
compdef _git_mate_complete {NAME}"#;

const BASH_COMPLETION: &str = r#"function _git_mate_complete() {
    local IFS=$'\n'
    COMPREPLY=()
    while IFS= read -r line; do COMPREPLY+=("$line"); done \
      < <(COMPLETE=bash command git-mate -- "${COMP_WORDS[@]:1}" 2>/dev/null)
}
complete -F _git_mate_complete git-mate
complete -F _git_mate_complete {NAME}"#;
