#[derive(clap::ValueEnum, Clone)]
pub enum Shell {
    Zsh,
    Bash,
}

#[derive(clap::Args)]
pub struct InitArgs {
    pub shell: Shell,
    /// Override the shell wrapper function name (default: git)
    #[arg(long)]
    pub wrapper_name: Option<String>,
}

pub fn run(args: InitArgs) -> Result<(), String> {
    let name = args
        .wrapper_name
        .or_else(|| crate::git::config::read_string("mate.wrapperName"))
        .unwrap_or_else(|| "git".to_string());

    match args.shell {
        Shell::Zsh => print!("{}", shell_init(&name, "zsh")),
        Shell::Bash => print!("{}", shell_init(&name, "bash")),
    }
    Ok(())
}

fn shell_init(name: &str, shell: &str) -> String {
    INIT_TEMPLATE
        .replace("{SHELL}", shell)
        .replace("{NAME}", name)
}

const INIT_TEMPLATE: &str = r#"# git-mate shell integration — generated by `git mate init {SHELL}`
# Add to ~/.{SHELL}rc: eval "$(git mate init {SHELL})"

function {NAME}() {
    case "$1" in
        co)     _git_mate_co     "${@:2}" ;;
        new)    _git_mate_new    "${@:2}" ;;
        finish) _git_mate_finish "${@:2}" ;;
        *)      command git "$@" ;;
    esac
}

function _git_mate_co() {
    local stdout exit_code cd_path
    stdout=$(command git mate checkout "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}

function _git_mate_new() {
    local stdout exit_code cd_path
    stdout=$(command git mate new "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}

function _git_mate_finish() {
    local stdout exit_code cd_path
    stdout=$(command git mate finish "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}
"#;
