#[derive(clap::ValueEnum, Clone)]
pub enum Shell {
    Zsh,
    Bash,
}

#[derive(clap::Args)]
pub struct InitArgs {
    pub shell: Shell,
}

pub fn run(args: InitArgs) -> Result<(), String> {
    match args.shell {
        Shell::Zsh => print!("{}", ZSH_INIT),
        Shell::Bash => print!("{}", BASH_INIT),
    }
    Ok(())
}

const ZSH_INIT: &str = r#"# git-mate shell integration — generated by `git mate init zsh`
# Add to ~/.zshrc: eval "$(git mate init zsh)"

function git() {
    case "$1" in
        co)     _git_mate_co     "${@:2}" ;;
        new)    _git_mate_new    "${@:2}" ;;
        finish) _git_mate_finish "${@:2}" ;;
        *)      command git "$@" ;;
    esac
}

function _git_mate_co() {
    local stdout exit_code cd_path
    stdout=$(command git mate checkout "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}

function _git_mate_new() {
    local stdout exit_code cd_path
    stdout=$(command git mate new "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}

function _git_mate_finish() {
    local stdout exit_code cd_path
    stdout=$(command git mate finish "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}
"#;

const BASH_INIT: &str = r#"# git-mate shell integration — generated by `git mate init bash`
# Add to ~/.bashrc: eval "$(git mate init bash)"

function git() {
    case "$1" in
        co)     _git_mate_co     "${@:2}" ;;
        new)    _git_mate_new    "${@:2}" ;;
        finish) _git_mate_finish "${@:2}" ;;
        *)      command git "$@" ;;
    esac
}

function _git_mate_co() {
    local stdout exit_code cd_path
    stdout=$(command git mate checkout "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}

function _git_mate_new() {
    local stdout exit_code cd_path
    stdout=$(command git mate new "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}

function _git_mate_finish() {
    local stdout exit_code cd_path
    stdout=$(command git mate finish "$@")
    exit_code=$?
    cd_path=$(printf '%s\n' "$stdout" | grep '^_MATE_CD:' | head -1 | sed 's/^_MATE_CD://')
    printf '%s\n' "$stdout" | grep -v '^_MATE_CD:'
    [[ $exit_code -eq 0 && -n "$cd_path" ]] && builtin cd "$cd_path"
    return $exit_code
}
"#;
