pub fn emit_init_script() {
    print!("{}", HEADER);
    print!("{}", AUTO_CD_WRAPPER);
    print!("{}", COMPLETION);
}

const HEADER: &str = r#"
# git-mate shell integration — generated by `mate init bash`
# Add this to your ~/.bashrc:
#   eval "$(command mate init bash)"
"#;

const AUTO_CD_WRAPPER: &str = r#"
# Auto-cd support
mate() {
    local _proto _exit
    _proto=$(mktemp) || return 1
    GIT_MATE_SHELL=1 command mate "$@" | command mate _protocol collect "$_proto"
    _exit=${PIPESTATUS[0]}
    eval "$(command mate _protocol interpret --bash "$_proto")"
    rm -f "$_proto"
    return $_exit
}
"#;

const COMPLETION: &str = r#"
# Shell completions
source <(COMPLETE=bash command mate)
"#;
