pub fn emit_init_script() {
    print!("{}", HEADER);
    print!("{}", AUTO_CD_WRAPPER);
    print!("{}", COMPLETION);
}

const HEADER: &str = r#"
# git-mate shell integration — generated by `git-mate init bash`
# Add this to your ~/.bashrc:
#   eval "$(command git-mate init bash)"
"#;

const AUTO_CD_WRAPPER: &str = r#"
# Auto-cd support
git-mate() {
    local tmpfile exit_code target_dir
    tmpfile=$(mktemp) || return 1
    GIT_MATE_SHELL=1 command git-mate "$@" > "$tmpfile"
    exit_code=$?
    target_dir=$(grep '^_MATE_CD:' "$tmpfile" | tail -n1 | sed 's/^_MATE_CD://')
    grep -v '^_MATE_CD:' "$tmpfile"
    rm -f "$tmpfile"
    if [[ -n "$target_dir" ]]; then
        builtin cd "$target_dir"
    fi
    return $exit_code
}
"#;

const COMPLETION: &str = r#"
# Shell completions
source <(COMPLETE=bash command git-mate)
"#;
