use crate::cmd::init::ShellIntegration;

pub fn emit_init_script(integration: ShellIntegration) {
    print!("{}", HEADER);
    match integration {
        ShellIntegration::False => {}
        ShellIntegration::True => print!("{}", SAFE_WRAPPER),
        ShellIntegration::Force => print!("{}", FORCE_WRAPPER),
    }
    print!("{}", COMPLETION);
}

const HEADER: &str = r#"
# git-mate shell integration — generated by `git-mate init bash`
# Add this to your ~/.bashrc:
#   eval "$(command git-mate init bash)"
"#;

const FORCE_WRAPPER: &str = r#"
# Auto-cd support
git() {
    local _proto _exit
    _proto=$(mktemp) || return 1
    GIT_MATE_PROTO="$_proto" command git "$@"
    _exit=$?
    eval "$(command git-mate _protocol --bash "$_proto")"
    rm -f "$_proto"
    return $_exit
}
"#;

const SAFE_WRAPPER: &str = r#"
# Auto-cd support
if [[ "$(type -t git 2>/dev/null)" == "function" ]]; then
    echo "git-mate: warning: 'git' is already a shell function; skipping git() wrapper. Set mate.shellIntegration=force to override." >&2
else
    git() {
        local _proto _exit
        _proto=$(mktemp) || return 1
        GIT_MATE_PROTO="$_proto" command git "$@"
        _exit=$?
        eval "$(command git-mate _protocol --bash "$_proto")"
        rm -f "$_proto"
        return $_exit
    }
fi
"#;

const COMPLETION: &str = r#"
# Shell completions
source <(COMPLETE=bash command git-mate)
"#;
