use crate::cmd::init::ShellIntegration;

pub fn emit_init_script(integration: ShellIntegration) {
    print!("{}", HEADER);
    match integration {
        ShellIntegration::False => {}
        ShellIntegration::True => print!("{}", SAFE_WRAPPER),
        ShellIntegration::Force => print!("{}", FORCE_WRAPPER),
    }
    print!("{}", COMPLETION);
}

const HEADER: &str = r#"
# git-mate shell integration — generated by `git-mate init pwsh`
# Add this to your PowerShell profile ($PROFILE):
#   & git-mate init pwsh | Invoke-Expression
"#;

const FORCE_WRAPPER: &str = r#"
# Auto-cd support
function git {
    $proto = [System.IO.Path]::GetTempFileName()
    $exitCode = -1
    try {
        $env:GIT_MATE_PROTO = $proto
        & (Get-Command -Name git -CommandType Application) @args
        $exitCode = $LASTEXITCODE
    } finally {
        $env:GIT_MATE_PROTO = $null
        & git-mate _protocol --pwsh $proto | Invoke-Expression
        Remove-Item $proto -ErrorAction SilentlyContinue
        $global:LASTEXITCODE = $exitCode
    }
}
"#;

const SAFE_WRAPPER: &str = r#"
# Auto-cd support
if ((Get-Command git -ErrorAction SilentlyContinue).CommandType -eq 'Function') {
    Write-Warning "git-mate: 'git' is already a shell function; skipping git() wrapper. Set mate.shellIntegration=force to override."
} else {
    function git {
        $proto = [System.IO.Path]::GetTempFileName()
        $exitCode = -1
        try {
            $env:GIT_MATE_PROTO = $proto
            & (Get-Command -Name git -CommandType Application) @args
            $exitCode = $LASTEXITCODE
        } finally {
            $env:GIT_MATE_PROTO = $null
            & git-mate _protocol --pwsh $proto | Invoke-Expression
            Remove-Item $proto -ErrorAction SilentlyContinue
            $global:LASTEXITCODE = $exitCode
        }
    }
}
"#;

const COMPLETION: &str = r#"
# Shell completions for `git-mate` and `git mate`
$env:COMPLETE = 'powershell'
& git-mate | Invoke-Expression
Remove-Item Env:\COMPLETE -ErrorAction SilentlyContinue
"#;
