pub fn emit_init_script() {
    print!("{}", HEADER);
    print!("{}", AUTO_CD_WRAPPER);
    print!("{}", COMPLETION);
}

const HEADER: &str = r#"
# git-mate shell integration — generated by `mate init zsh`
# Add this to your ~/.zshrc:
#   eval "$(command mate init zsh)"
"#;

const AUTO_CD_WRAPPER: &str = r#"
# Auto-cd support
function mate() {
    local _proto _exit
    _proto=$(mktemp) || return 1
    GIT_MATE_PROTO="$_proto" command mate "$@"
    _exit=$?
    eval "$(command mate _protocol --zsh "$_proto")"
    rm -f "$_proto"
    return $_exit
}
"#;

const COMPLETION: &str = r#"
# Shell completions
source <(COMPLETE=zsh command mate)
"#;
